### ISSUE TITLE
TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by alexsantos** [moszeed/easysoap#12]
I'm testing easysoap with a public and simple webservice from http://oracle-base.com/articles/9i/consuming-web-services-9i.php.
The WSDL is http://oracle-base.com/webservices/server.php?wsdl

What I've found is that the function searchNode(node, name) receives null as the node parameter, so node.children raises an error.

If I test for null before testing for node.children

```javascript
        if (node === null || node.children === void 0 ||
            node.children === null   ||
            _.isEmpty(node.children)) {
            return false;
        }
````

then I get a TypeError: Cannot read property 'attr' of undefined at line 352, when the function
```javascript
    getNamespace(methodRequest.attr.message)
````
is called.

The first error occurs when "input" is passed as the name parameter, so methodRequest is undefined

**Comment by AlexSantos** [comment]
I've been reading your code and it seems that this wsdl won't work because there aren't any <element> tags on the types definition.

**Comment by moszeed** [comment]
Hi, sry for the long delay. 
I`m currently very busy, but i`m open for Pull Request if you already fixed it in your code.
But will also look into this, maybe took a while.

**Comment by avindra** [comment]
Hi moszeed, do you have any recommendations for a soap library in node.js or otherwise? We are looking for a soap client that supports multipart messages. Does this library support multipart messages?

**Comment by moszeed** [comment]
Hi, first error should be fixed now, i published a version that has a "is available check".
