### ISSUE TITLE
Self-signed certificate failue

### ISSUE THREAD

**Issue by yarons-fring** [moszeed/easysoap#14]
Hi,
I used the basic form (as the example you provided suggests) and even when changing to unsecure:

```javascript
var clientOptions = {
  secure : false
};
```

And I got the following error:
```
{ [Error: self signed certificate] code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
```

Thanks!

**Comment by moszeed** [comment]
Hi, 
your *clientParams* is missing the option *rejectUnauthorized  : false* for testing.

**Comment by yarons-fring** [comment]
Still some error but no the same one, guess it's OK then, thanks.

**Comment by followthekoden** [comment]
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

worked for me
