### ISSUE TITLE
What compiler is this using?

### ISSUE THREAD

**Issue by denisbetsi** [moszeed/easysoap#20]
I see references like (values) => {    vs function(values) {    and so default npm install easysoap doesn't work. What am I missing?

**Comment by moszeed** [comment]
hi, there is no compiler, 
this is ES6 Syntax (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions), you need to install a Node.js Version greater or equal 4.0.0 ...
