### ISSUE TITLE
Cannot handle one-method definition the proper way

### ISSUE THREAD

**Issue by 39dotyt** [moszeed/easysoap#22]
For example, from this link

https://webservices.optimalpayments.com/ilsWS/IlsService/v1?wsdl

easysoap.getMethodParamsByName will fail, when other clients, such as Boomerang will display it the proper way.

**Comment by moszeed** [comment]
Hi and thanks for the Error report.
I updated the "wsdlrdr" dependencies with a fix for that.
Maybe you can check and report back.
Thx
