### ISSUE TITLE
Advanced params

### ISSUE THREAD

**Issue by andypanda** [moszeed/easysoap#27]
Hi everyone and thanks for a great client,

my problem is that I need to create more advanced parameteres than just simple strings - when calling a web service.

**1) THE SERVICE I NEED TO USE**
This is the url: http://sis.kolumbus.no:90/SXWS/SXService.svc?wsdl
The method is called **GetSituationExchange**

Here is a SOAP request that _works_(i have tested it):

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:siri="http://www.kolumbus.no/siri" xmlns:siri1="http://www.siri.org.uk/siri" xmlns:acsb="http://www.ifopt.org.uk/acsb">
   <soapenv:Header/>
   <soapenv:Body>
      <siri:GetSituationExchange>
         <ServiceRequestInfo>
            <siri1:RequestTimestamp>2013-05-22T12:20:40+02:00</siri1:RequestTimestamp>
            <siri1:RequestorRef>SWM</siri1:RequestorRef>
         </ServiceRequestInfo>
         <Request version="1.4">
            <siri1:RequestTimestamp>2013-05-22T12:20:40+02:00</siri1:RequestTimestamp>
         </Request>
         <RequestExtension>
            
         </RequestExtension>
      </siri:GetSituationExchange>
   </soapenv:Body>
</soapenv:Envelope>`

**2) MY PROBLEM**
Is that i need to create those three parameters; ServiceRequestInfo, Request and RequestExtension - but since they have _complex parameters within them_ – i dont know how to do it! All examples I have found just uses strings.

**2) THE CODE OF MYE CLIENT**

   `var easysoap = require('easysoap');
    var params = {
        host   : 'http://sis.kolumbus.no:90',
        path   : '/SXWS/SXService.svc',
        wsdl   : '/SXWS/SXService.svc?wsdl'
    }
var soapClient = easysoap.createClient(params);

```
soapClient.getAllFunctions()
        .then((functionArray) => { 
            console.log(functionArray);     
        })
        .catch((err) => { 

        throw new Error(err);
         });


        soapClient.getMethodParamsByName('GetSituationExchange')
            .then((methodParams) => { 

            console.log(methodParams.request); 
        })
        .catch((err) => { throw new Error(err); });



 soapClient.call({
        method    : 'GetSituationExchange',
        params: {
            ServiceRequestInfo: {
                params: {
                    RequestTimestamp: {
                        '_value'     : '2013-05-22T12:20:40+02:00'
                    },
                    RequestorRef: {
                        '_value'     : 'SWM'
                    }
                }
            },
            Request: {
                params: {
                    RequestTimestamp: {
                        '_value'     : '2013-05-22T12:20:40+02:00'
                    }                    
                }
            },
            RequestExtension: ""                   
        } 

    })
    .then((callResponse) => { 
        console.log(callResponse.data); // response data as json
        console.log(callResponse.body); // response body
        console.log(callResponse.header);  //response header

    })
    .catch((err) => { 
        console.log(err);
    throw new Error(err); });`
```

**4) THE RESULT OF THE LOG WHEN RUNNING THE CODE**
`[ 'CheckStatus',
  'DeleteSubscription',
  'GetCapabilities',
  'GetSituationExchange',
  'Subscribe' ]

[ { name: 'ServiceRequestInfo',
    namespace: 'q1',
    type: 'ServiceRequestInfo',
    'xmlns:q1': 'http://www.siri.org.uk/siri' },
  { name: 'Request',
    namespace: 'q2',
    type: 'SituationExchangeRequest',
    'xmlns:q2': 'http://www.siri.org.uk/siri' },
  { name: 'RequestExtension',
    namespace: 'tns',
    type: 'ExtensionsStructure' } ]

{ Fault: 
   [ { faultcode: 'a:ActionNotSupported' },
     { faultstring: 'The message with Action \'\' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver.  Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).' } ] }`

Can anyone help me with this?
Kind Regards,
Anders

**Comment by bgardner87** [comment]
The error code you are getting is because you don't have a SOAPAction in your header:

const params = {
    host: 'demo.4levers.com',
    path: '/TxWs/ATPayTxWS.svc',
    wsdl: '/TxWs/ATPayTxWS.svc?singleWsdl',
    headers: [{
        name: 'SOAPAction',
        value: <web service url>
    }]
};

**Comment by moszeed** [comment]
"Good things come to those who wait" ^_^

so i close this, thx!
