### ISSUE TITLE
Better Examples Needed

### ISSUE THREAD

**Issue by ugommirikwe** [moszeed/easysoap#28]
Thanks for your package, but the example you provided in the Readme is quite vague -- how do you split a SOAP web service URL into the "host", "path" and "wsdl" parameters, for example? I keep getting "Error: no wsdl/xml response" message when I call the "createClient" method.

**Comment by moszeed** [comment]
Hi, maybe the Tests may help you 
https://github.com/moszeed/easysoap/blob/master/tests/tests.js

**Comment by pnnaj** [comment]
Hi I am having trouble calling http://www.thomas-bayer.com/axis2/services/BLZService.wsdl

My code is 
`(function() {
  "use strict";

  var easysoap = require('easysoap');

  // define soap params
  var params = {
      host: 'http://www.thomas-bayer.com',
      path: '/axis2/services/',
      wsdl: '/axis2/services/BLZService?WSDL'
      /*headers: [{
          'name': 'item_name',
          'value': 'item_value',
          'namespace': 'item_namespace'
      }]*/
  }

  console.log("START SOAP TEST");

  /*
   * create the client
   */
  var soapClient = easysoap.createClient(params);


  /*
   * get all available functions
   */
  soapClient.getAllFunctions()
      .then(function(functionArray){
          console.log(functionArray);
      })
      .catch((err) => {
          throw new Error(err);
      });


  /*
   * get the method params by given methodName
   */
  /*soapClient.getMethodParamsByName('getBank')
      .then((methodParams) => {
          console.log(methodParams.request);
          console.log(methodParams.response);
      })
      .catch((err) => {
          throw new Error(err);
      });*/


  /*
   * call soap method
   */
  soapClient.call({
          method: 'getBank',
          attributes: {
              xmlns: 'http://thomas-bayer.com/blz/'
          },
          params: {
              blz: '36010424'
          }
      })
      .then((callResponse) => {
          console.log(callResponse.data); // response data as json
          console.log(callResponse.body); // response body
          console.log(callResponse.header); //response header
      })
      .catch((err) => {
          throw new Error(err);
      });

})();`

and I get 

START SOAP TEST
[ 'getBank' ]
{ Exception: 'org.apache.axis2.AxisFault: The service cannot be found for the endpoint reference (EPR) http://www.thomas
-bayer.com/axis2/services/\n\tat org.apache.axis2.engine.DispatchPhase.checkPostConditions(DispatchPhase.java:62)\n\tat
org.apache.axis2.engine.Phase.invoke(Phase.java:308)\n\tat org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:212
)\n\tat org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:132)\n\tat org.apache.axis2.transport.http.HTTPTransp
ortUtils.processHTTPPostRequest(HTTPTransportUtils.java:275)\n\tat org.apache.axis2.transport.http.AxisServlet.doPost(Ax
isServlet.java:120)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:646)\n\tat javax.servlet.http.HttpServ
let.service(HttpServlet.java:727)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:303)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\n\tat
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)\n\tat org.apache.catalina.core.Stand
ardContextValve.invoke(StandardContextValve.java:122)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(A
uthenticatorBase.java:501)\n\tat org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)\n\tat org.apa
che.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)\n\tat org.apache.catalina.valves.ErrorReportValve
.invoke(ErrorReportValve.java:98)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116
)\n\tat org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)\n\tat org.apache.catalina.connector.Coyo
teAdapter.service(CoyoteAdapter.java:408)\n\tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11P
rocessor.java:1041)\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607
)\n\tat org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)\n\tat java.util.concurrent.Thre
adPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPo
olExecutor.java:615)\n\tat java.lang.Thread.run(Thread.java:745)\n' }
undefined
undefined

Please help
