### ISSUE TITLE
Authenticate with Username and Password

### ISSUE THREAD

**Issue by Alpha-X15** [moszeed/easysoap#29]
Hello everybody,
is there a way to authenticate using easysoap at the specified WSDL?
Just as it is possible with other SOAP clients, such as e.g. at _npm soap_ with:
`client.setSecurity(new soap.BasicAuthSecurity('username', 'password'));`
or with _soapjs_ :

```
var c = soap.createClient(wsdl, {
    username: 'username',
    password: 'password'
});
```

It would be very nice if such a function could be included. Have done so far only good experiences with easysoap.
Thank you very much!

**Comment by i8wu** [comment]
@Alpha-X15 Did you ever get authentication working?

**Comment by moszeed** [comment]
@Alpha-X15 @i8wu basic Authentication is supported trough the Headers, for example:

`        
const uname = 'Username';
const pword = 'Password';

const params = {
  headers : {
      'Authorization' : 'Basic ' + new Buffer(uname + ':' + pword).toString('base64'),
      'user-agent'    : 'MySoapClient',
      'Content-Type'  : 'text/plain;charset=UTF-8'
  }
}

const soapClient = easysoap.createClient(params);
`
