### ISSUE TITLE
Two typos in your how to use

### ISSUE THREAD

**Issue by ozette** [moszeed/easysoap#30]
First of all, thanks for authoring easysoap.

This may be trivial, but there are two typos in your _How to use_ demo.
1. in the params variable, the '/path/wsdl is missing a trailing single quote character.
2. the part where getMethodParamsByName is called says respone instead of **response**.

**Comment by bchmura** [comment]
Can confirm, came to let you know the exact same thing

**Comment by moszeed** [comment]
=) thanks ... fixed!
