### ISSUE TITLE
Error: No XML to parse!

### ISSUE THREAD

**Issue by ecellani** [moszeed/easysoap#32]
Hi folks,

I am trying to do a simple request and I am getting the follwing error:

> Error: No XML to parse!
>    at new XmlDocument (<HOME>/node_modules/xmldoc/lib/xmldoc.js:188:11)
>    at Object.Wsdlrdr.getXmlDataAsJson (<HOME>/node_modules/wsdlrdr/src/index.js:390:27)
>    at wsdlrdr.getMethodParamsByName.then (<HOME>/node_modules/easysoap/src/easysoap.js:56:58)

```
client.call({
    'method' : 'generate',
    'params' : args
}).then((callResponse) => {
    console.log(callResponse.data);
    console.log(callResponse.body);
    console.log(callResponse.header);
}).catch((err) => {
    console.log(err)
});
```

at `easysoap.js:56:` the `soapResponse.body` is empty! Am I doing something wrong?

Thanks in advance!

**Comment by moszeed** [comment]
Is your "wsdl" a valid XML ?

**Comment by ecellani** [comment]
Hi,

Thanks for your reply!

Apparently the problem occurs because of the content-type of the request header. But I don't know how set a different content-type.

Best regards!

**Comment by moszeed** [comment]
hi, sry for the long delay..
i currently extended the content-type, can you pleasy try if this solves your problem ?

**Comment by ozette** [comment]
I'm having this issue with easysoap 1.0.6, and find trouble updating this library.
On node v10.7 I receive Unexpected token function on the 'async' code lines. Ideas?
