### ISSUE TITLE
Documentation for attributes parameter of call method

### ISSUE THREAD

**Issue by heretogo** [moszeed/easysoap#38]
I am trying to configure a node.js app to consume a SOAP service for an SSL provider. I am able to call  getAllFunctions and getMethodParamsByName without a problem but I am unable to actually call a soap method. The call fails silent so I'm not sure where the problem is.

As a test example, getWebServiceInfo is a method that an unauthenticated user may call with no parameters.

```
soapClient.call({
    method    : 'getWebServiceInfo',
    params: {
    }
})
.then((callResponse) => {
    console.log(callResponse.data); // response data as json
    console.log(callResponse.body); // response body
    console.log(callResponse.header);  //response header
})
.catch((err) => { throw new Error(err); });
```

Is there something I'm missing configuration wise? I am basing my node project off a script I wrote using the suds library in Python. Suds just works and exposes a function to instantiate a parameter objects based on its wsdl definition.

Any help would be appreciated.

**Comment by moszeed** [comment]
Hi, 
maybe it helps if you add some log-output to the request.js
https://github.com/moszeed/easysoap/blob/master/src/request/request.js#L279

to look what the server really says ....
