### ISSUE TITLE
How to set soapAction?

### ISSUE THREAD

**Issue by mezerotm** [moszeed/easysoap#42]
When making a call I get
```
{
    Fault: [ 
        { faultcode: 'soap:Client' },
        { faultstring: 'System.Web.Services.Protocols.SoapException: Unable to handle request without a valid action parameter. Please supply a valid soap action.\r\n   at System.Web.Services.Protocols.Soap12ServerProtocolHelper.RouteRequest()\r\n   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()\r\n   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean& abortProcessing)' },
        { detail: '' } 
    ]
}
```
After doing some research I found out that my header needs to include a field called `soapAction` looking over the API i'm trying to use the soap action seems to change with each request. I'v already tried including the headers when I create my `soapClient` but this still doesn't affect anything.

A side question which would help further: 
Is there a way to see what is being sent when I make a call with easysoap to see what kind of request is being made.

**Comment by moszeed** [comment]
You can use the ```getRequestXml``` to get the created XML that will be used in the request.

The default way to set ```soapAction``` is trough the ```headers``` option:

```
    headers: {
        'soapAction': 'something cool here'
    }
```
