### ISSUE TITLE
TypeError: fs.stat is not a function

### ISSUE THREAD

**Issue by Roshdy** [moszeed/easysoap#44]
I'm trying to follow the example in a ReactJS app, I'm using it this way

```
import EasySoap from 'easysoap';
...
componentDidMount(){
  let params = {
    host  : 'http://www.xignite.com/',
    path  : 'xcurrencies.asmx',
    wsdl  : '?wsdl'
  };

  var soapClient = EasySoap(params);

  soapClient.getAllFunctions()
    .then((functionArray) => { 
      console.log(functionArray); 
    })
    .catch((err) => { 
      throw new Error(err); 
    });
}
```

and i'm getting the error:
`Uncaught (in promise) Error: Error: TypeError: fs.stat is not a function`

**Comment by bunower** [comment]
Did you solved that Problem?

**Comment by moszeed** [comment]
maybe this error is coming because you`re using easysoap in browser context, but that is not possible.
