### ISSUE TITLE
Attributes in XML now shown.

### ISSUE THREAD

**Issue by nexflo** [moszeed/easysoap#45]
Got an XML with attributes, these are not parsed into the JSON tho:

<?xml version="1.0" encoding="UTF-8" standalone="no"?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns7:getManufacturersResponse xmlns:ns7="XXX">

<manufacturer key="20" value="Abarth"/><manufacturer key="40" value="Alfa Romeo"/

becomes:  { manufacturer: '' },

**Comment by moszeed** [comment]
hi, is there a SOAP Service where i can test this?

**Comment by moszeed** [comment]
this should now work with version 2.1.0
