### ISSUE TITLE
no SOAPAction Header

### ISSUE THREAD

**Issue by suresh1271** [moszeed/easysoap#46]
Hi All, What is the value of SOAPAction header in a wsdl. Is it same value of method what we are calling or a different value?. As I could see in my wsdl it is the method name but when i pass the value as SOAPAction header the response i am getting is No SOAPAction Header. Can anyone please give me solution. Thanks in advance.

**Comment by kennysmoothx** [comment]
I am experiencing the same error,

Have you found a solution?

**Comment by ctpmp** [comment]
try adding it as an empty header
```
params.headers: {SOAPAction: ''}
client = EasySoap(params, opts)
```

**Comment by moszeed** [comment]
@suresh1271 

SOAP 1.1 Specification: https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383528

```
The SOAPAction HTTP request header field can be used to indicate the intent of the SOAP HTTP request.
The value is a URI identifying the intent. SOAP places no restrictions on the format or specificity of the 
URI or that it is resolvable. An HTTP client MUST use this header field when issuing a SOAP HTTP 
Request. The presence and content of the SOAPAction header field can be used by servers such as 
firewalls to appropriately filter SOAP request messages in HTTP. The header field value of empty string 
("") means that the intent of the SOAP message is provided by the HTTP Request-URI. No value means 
that there is no indication of the intent of the message.
```

and @ctpmp is right it will be added ass `params.headers.SOAPAction` 👍 

i will close this issue for now, if something will not work as expected then feel free to respond and i will reopen this ...
